WTF_CSRF_ENABLED = True
SECRET_KEY = 'A0Zr98j/3yX R~XHH!jmN]LWX/,?RT'
MAIL_SERVER = "smtp.office365.com"
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USERNAME = "shauna.grieve@neueda.com"
MAIL_PASSWORD = "Uls13210902"
cleaning = 2
pest = 1
manager = 3
